apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    name: web-app
spec:
  containers:
  - name: cfk-web-app-container
    image: rootcfk/simple-webapp-color-arm
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: red
